require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MailerContentsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MailerContent. As you add validations to MailerContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailerContentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mailer_contents as @mailer_contents" do
      mailer_content = MailerContent.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mailer_contents)).to eq([mailer_content])
    end
  end

  describe "GET show" do
    it "assigns the requested mailer_content as @mailer_content" do
      mailer_content = MailerContent.create! valid_attributes
      get :show, {:id => mailer_content.to_param}, valid_session
      expect(assigns(:mailer_content)).to eq(mailer_content)
    end
  end

  describe "GET new" do
    it "assigns a new mailer_content as @mailer_content" do
      get :new, {}, valid_session
      expect(assigns(:mailer_content)).to be_a_new(MailerContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailer_content as @mailer_content" do
      mailer_content = MailerContent.create! valid_attributes
      get :edit, {:id => mailer_content.to_param}, valid_session
      expect(assigns(:mailer_content)).to eq(mailer_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailerContent" do
        expect {
          post :create, {:mailer_content => valid_attributes}, valid_session
        }.to change(MailerContent, :count).by(1)
      end

      it "assigns a newly created mailer_content as @mailer_content" do
        post :create, {:mailer_content => valid_attributes}, valid_session
        expect(assigns(:mailer_content)).to be_a(MailerContent)
        expect(assigns(:mailer_content)).to be_persisted
      end

      it "redirects to the created mailer_content" do
        post :create, {:mailer_content => valid_attributes}, valid_session
        expect(response).to redirect_to(MailerContent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailer_content as @mailer_content" do
        post :create, {:mailer_content => invalid_attributes}, valid_session
        expect(assigns(:mailer_content)).to be_a_new(MailerContent)
      end

      it "re-renders the 'new' template" do
        post :create, {:mailer_content => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mailer_content" do
        mailer_content = MailerContent.create! valid_attributes
        put :update, {:id => mailer_content.to_param, :mailer_content => new_attributes}, valid_session
        mailer_content.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mailer_content as @mailer_content" do
        mailer_content = MailerContent.create! valid_attributes
        put :update, {:id => mailer_content.to_param, :mailer_content => valid_attributes}, valid_session
        expect(assigns(:mailer_content)).to eq(mailer_content)
      end

      it "redirects to the mailer_content" do
        mailer_content = MailerContent.create! valid_attributes
        put :update, {:id => mailer_content.to_param, :mailer_content => valid_attributes}, valid_session
        expect(response).to redirect_to(mailer_content)
      end
    end

    describe "with invalid params" do
      it "assigns the mailer_content as @mailer_content" do
        mailer_content = MailerContent.create! valid_attributes
        put :update, {:id => mailer_content.to_param, :mailer_content => invalid_attributes}, valid_session
        expect(assigns(:mailer_content)).to eq(mailer_content)
      end

      it "re-renders the 'edit' template" do
        mailer_content = MailerContent.create! valid_attributes
        put :update, {:id => mailer_content.to_param, :mailer_content => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailer_content" do
      mailer_content = MailerContent.create! valid_attributes
      expect {
        delete :destroy, {:id => mailer_content.to_param}, valid_session
      }.to change(MailerContent, :count).by(-1)
    end

    it "redirects to the mailer_contents list" do
      mailer_content = MailerContent.create! valid_attributes
      delete :destroy, {:id => mailer_content.to_param}, valid_session
      expect(response).to redirect_to(mailer_contents_url)
    end
  end

end
